### ISSUE TITLE
Rename to WebAPIKit?

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/WebAPIKit#22]
It looks we're going to host not only DOM APIs here, but all Web APIs. Maybe let's rename the library before we've tagged the first release, to avoid the confusion?

**Comment by j-f1** [comment]
That sounds good to me!

**Comment by MaxDesiatov** [comment]
@kateinoigakukun I'm interested in your opinion to get some kind of consensus from maintainers active in this repository 🙂

**Comment by kateinoigakukun** [comment]
Sounds good to me 👍 
I confirmed that there is no public library with the same name https://sourcegraph.com/search?q=context:global+repo:WebAPIKit&patternType=literal
